### ISSUE TITLE
Property.value(E... value) is misleading

### ISSUE THREAD

**Issue by asomov** [Wolfgang-Schuetzelhofer/jcypher#16]
Variable Length Argument Lists in Java is used in general in a context where regardless of the amount of given arguments the same logic is applied.
But Property.value(E... value) and Property.value(value) work differently if one argument is provided.

To avoid confusion it would be nice to use different names for these methods to indicate different usage:
Property.value(value)
Property.values(E... value)

With different names it would be clear what happens with these method invocations:
Property.value(1)
Property.values(1)

**Comment by Wolfgang-Schuetzelhofer** [comment]
proposed changes will be in next release.
