### ISSUE TITLE
What about Mapping of Lists of Complex Objects

### ISSUE THREAD

**Issue by ghost** [Wolfgang-Schuetzelhofer/jcypher#30]
Hello!

When i map an Object, primitive fields will be mapped to Node properties, complex types will be mapped to other nodes and linked to the parent.

How can i map a field which is a collections of Complex Types, which means to map it to several nodes of the Type of the List and link them to the parent. Is there a possibility or a workaround, other than a bottom up approach to realize this? It doesnt work if i just put a field of Collection Type in the class of which i intend to map the object.

Thanks in advance!

Philipp

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hi Philipp,

The field should be of type *java.util.List* or a subtype thereof and can
contain (arbitrarily) complex objects. Please try it. If it does not work,
I will send a working example.

Best regards,
Wolfgang
