### ISSUE TITLE
Make the registerShutdownHook optional

### ISSUE THREAD

**Issue by jknack** [Wolfgang-Schuetzelhofer/jcypher#32]
May be using a system properties or similar.

It is nice to turn off shutdown hook in managed environment, where there are explicit start/stop lifecycle events.

Thanks

**Comment by Wolfgang-Schuetzelhofer** [comment]
Dear Edgar,

I will make the **registerShutdownHook** opional in the next release, planned for July.

Best regards,
Wolfgang
