### ISSUE TITLE
make dbaccess implementation fully configurable at instantiation time

### ISSUE THREAD

**Issue by jknack** [Wolfgang-Schuetzelhofer/jcypher#33]
`DBAccessFactory` it is nice for quick start, but will be nice to have a way to manually instantiated/configure `DBAccess` implementations.

For example make `BoltDBAccess` fully configurable via constructor:

```java
public BoltDBAccess(Driver driver) {
  ...
}

public BoltDBAccess(String uri, AuthToken token) {
  ...
}

```

Similar for embedded implementation:

```java
public EmbeddedDBAccess(GraphDatabaseService db) {
  ...
}
```

Each implementation has a clear contract of what dependencies needs.

Here are some other benefits of such solution:

- Fix #31, due user can manually create and provide they own GraphDatabaseService
- Today the implementations filter out some properties, so we can fully configure a GraphDatabaseService or Driver

What do you think?

**Comment by Wolfgang-Schuetzelhofer** [comment]
Good idea,
I will consider this for the next release.

Best regards
