### ISSUE TITLE
Match Node with ID

### ISSUE THREAD

**Issue by utkarsh3107** [Wolfgang-Schuetzelhofer/jcypher#35]
I'm sorry if this seems to vague but I would like to know how I can make the below cypher:

```
MATCH (N)
 WHERE id(N) = <some_node_id>
 return N;
```

**Comment by Wolfgang-Schuetzelhofer** [comment]
Sorry for the late answer,
if you have a node id you should better use START like so:
clauses = new IClause[]{
				START.node(n).byId(1234),
				RETURN.value(n)
		};

this translates to the following CYPHER expression:
START n = node(1234)
RETURN n

best regards,
Wolfgang
