### ISSUE TITLE
LocalDateTime mapping issue and custom mappings.

### ISSUE THREAD

**Issue by fredrikB1** [Wolfgang-Schuetzelhofer/jcypher#37]
Hello! 

JCypher's doesn't seem to support converison of Java LocalDateTime, at least in the sense that a LocalDateTime object is converted to numerous nodes when desired is to keep the date as a single property on a single node. Is there a known workaround to this issue?  

Similarly, is there any possibility to introduce custom mappings? We haven't at least been able to find any such support. The setting that we have is that we use wrappers of primitives and strings and preferably want to set the wrapping object to the contained primitive in the database.

Best regards,
Fredrik

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hello Fredrik,

I have just returned from the Cape Verde
<https://www.dict.cc/englisch-deutsch/Verde.html> Islands
<https://www.dict.cc/englisch-deutsch/Islands.html> (I have been on a
Sailing trip there).
Please give me a few days to look into your matter.
I will return to you with an answer and hopefully a solution by end of this
week.

Best regards,
Wolfgang

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hello Fredrik,
currently there is no possibility to define custom mappings (from arbitrary classes to primitives) within JCypher. Such a mapping has to be done somewhere at the application level.
I will consider a mechanism and an according hook within the framework which will allow to register such mappings for the next release.

Best regards,
Wolfgang

**Comment by sirolf2009** [comment]
Could you add the possibility for custom label mapping as well?
I have 2 domain classes that both implement an interface. When I save them now, both nodes just get the name of the class as label and so the information that they implement the interface is lost., making writing queries much harder. A label mapper would be perfect for this as I could make a custom mapper that adds both labels

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hello Fredrik,
sorry to say, but custom mappings won't come soon with JCypher. It would require some major redesign at the core level. As I am currently engaged int two projects, I don't have the time for such an effort.
I would suggest, doing appropriate transformations above the framework layer.
If however you want to extend JCypher to provide better support for your problems, I am always happy for contributions.
Sorry that I am currently not able to provide more support.
Best regards,
Wolfgang
