### ISSUE TITLE
transaction docs missing!

### ISSUE THREAD

**Issue by Infiniverse** [Wolfgang-Schuetzelhofer/jcypher#4]
Hi there, I've been through all the docs, but I can't find anything about how JCypher deals with transactions?

Is this missing from the docs?

Thanks,
Joe

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hi Joe,
currently every query is performed as a single transaction. A distinct transaction interface (begin, commit, rollback) will be part of one of the upcoming releases (2.7.0 or 2.8.0).

Best regards,
Wolfgang


-----Original Message-----

**Comment by Infiniverse** [comment]
Ahha, I guessed it was something like that.

I’m currently using SpringDataNeo4j - and want to get away from Spring as soon as possible. JCypher looks like an ideal candidate! :)

:)

Cheers,
Joe

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hi Joe,
sorry for my slow response, but I was on vacation on a sailing trip in the adreatic sea.
I will make a transaction api part of the next JCypher release (2.7.0)

Best regards,
Wolfgang


-----Original Message-----

**Comment by Infiniverse** [comment]
Very nice! :) Welcome back, and thanks for your feedback.
Merci,
Joe

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hi Joe,


JCypher 2.7.0 has been released today.
It now provides a transaction API. It's usage is documented in the wiki at:
P08 Transactions

Best regards,

Wolfgang



-----Original Message-----

**Comment by Infiniverse** [comment]
Cheers Wolfgang.

Looking forward to evaluating it. :)

Anything to get off spring! :)

Joe
