### ISSUE TITLE
Querying objects in memory using CYPHER queries

### ISSUE THREAD

**Issue by smichea** [Wolfgang-Schuetzelhofer/jcypher#54]
Not sure it is the right place to ask this question, so my apologies in advance if not.

Imagine i have a set of Pojo stored in memory (in lists, maps,...), can JCypher help me to filter them using Cypher queries ?

**Comment by Wolfgang-Schuetzelhofer** [comment]
Only in an indirect way.
You have to store the objects in a Neo4j database (can be an in memory db).
If you use the domain mapping approach that's straight forward.
Then you can use domain queries to do the filtering, or you can look at the created graph structure,
and us cypher (JCypher) queries.
For Domain mapping and domain queries look at the documentation starting at:
https://github.com/Wolfgang-Schuetzelhofer/jcypher/wiki/Domain-Mapping

Best regards,
Wolfgang

**Comment by smichea** [comment]
Thank you Wolfgang !
