### ISSUE TITLE
moving to Neo4J driver 4.0.0 and adding support for Neo4J 4.x.x

### ISSUE THREAD

**Issue by ashr123** [Wolfgang-Schuetzelhofer/jcypher#57]
Hey, when will you add support for the modern driver and DB? there was no progress since 2017

**Comment by Wolfgang-Schuetzelhofer** [comment]
Currently I have quite heavy workload on customer projects, so I don't know when I will be able to continue development on JCypher (I am sorry for that).
However, JCypher being an open source project, everybody is invited to contribute.

Best regards,
Wolfgang

**Comment by ashr123** [comment]
You are absolutely right, thank you for your answer, if peoples continue to develop this  framework, will you respond to pull requests and merge the improvements?

**Comment by Wolfgang-Schuetzelhofer** [comment]
Yes, I will respond to pull request and merge the improvements. I am happy about every contribution.

Best regards,
Wolfgang
